name = "aoc_2025"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gtempo = ">= 7.2.2 and < 8.0.0"

[dev-dependencies]
